Repository nikhilmufc7/Flutter_IeltsPrep, pull requests merged in 2020-10, with the labels that each got.

#4 resolved back button issue on premium screen when navigating
  lib/screens/forums_screen.dart
  lib/screens/premium_screen.dart
  lib/widgets/menu_page.dart
  pubspec.lock
  pubspec.yaml
Labels: hacktoberfest-accepted

#5 app close on back button press on home screen
  lib/screens/home_screen.dart
Labels: hacktoberfest-accepted

#8 README
  README.md
  screenshots/exercise_listening.png
  screenshots/exercise_reading.png
  screenshots/exercise_reading_2.png
  screenshots/exercise_speaking.png
  screenshots/exercise_writing.png
  screenshots/main_screen.png
  screenshots/menu.png
  screenshots/premium.png
  screenshots/quiz.png
  screenshots/quiz_2.png
  screenshots/quiz_3.png
  screenshots/signup.png
  screenshots/vocabulary.png
Labels: hacktoberfest, hacktoberfest-accepted

#9 Added tech stack
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted
